format_version: 10
pipelines:
  FreeWheelers:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-e09dcac:
        git: https://github.com/zaidmonis/FreeWheelers
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - Unit-Test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-unit-tests:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - test
                - FreeWheelers.UnitTests
                command: dotnet
                run_if: passed
    - build-and-deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy:
            timeout: 0
            tasks:
            - exec:
                arguments:
                  - up
                command: docker-compose
                working_directory: ./FreeWheelers
                run_if: passed