version: '3'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2022"
      MSSQL_PID: Express
    ports:
    - "1433:1433"
  product-api:
    build: .
    environment:
      DBServer: "ms-sql-server"
      DBUser: "SA"
      DBPassword: "Pa55w0rd2022"
      Database: "Products"
      DBPort: "1433"
    ports:
    - "8080:80"